### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by zzxp** [danini/graph-cut-ransac#1]
when I run your code with Visual studio 2015 and opencv 3,41,some problems happen,and I do not know how to solve them,could you tell me your Operating platform？

**Comment by danini** [comment]
Hey! Have you solved it in the meantime? It should work with it, what is the error message?

**Comment by zzxp** [comment]
void rpoly_ak1(double op[MDP1], int* Degree, double zeror[MAXDEGREE], double zeroi[MAXDEGREE]){
    int i, j, jj, l, N, NM1, NN, NZ, zerok;
error：”MDP1“ Undeclared identifier
           “MAXDEGREE”Undeclared identifier

**Comment by zzxp** [comment]
void rpoly_ak1(double op[MDP1], int* Degree, double zeror[MAXDEGREE], double zeroi[MAXDEGREE]){
int i, j, jj, l, N, NM1, NN, NZ, zerok;
error：”MDP1“ Undeclared identifier
           “MAXDEGREE”Undeclared identifier

**Comment by danini** [comment]
There should be these lines in the header file ("Rpoly.h"):
#define MAXDEGREE 100
#define MDP1 MAXDEGREE+1

**Comment by zzxp** [comment]
![1](https://user-images.githubusercontent.com/26996462/41855592-9c0d6a28-78c5-11e8-812e-4f4f8cb10b17.PNG)
