### ISSUE TITLE
error: ISO C++17 does       not allow 'register' storage class specifier [-Wregister]

### ISSUE THREAD

**Issue by zhleternity** [danini/graph-cut-ransac#13]
error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]

Excuse me ?How can i resolve thie issue?Thank you very much.

**Comment by ducha-aiki** [comment]
set(CMAKE_CXX_FLAGS "-fpermissive")

**Comment by zhleternity** [comment]
> set(CMAKE_CXX_FLAGS "-fpermissive")

thanks very much
