### ISSUE TITLE
AttributeError: module 'pygcransac' has no attribute findHomography

### ISSUE THREAD

**Issue by recepcanfa** [danini/graph-cut-ransac#14]
Hi, I installed pygcransac using "python setup.py install" without error, then I run example jupyter notebook in examples folder, I got AttributeError. How can I solve this problem?
![Capture](https://user-images.githubusercontent.com/28019160/72268272-912afe00-3632-11ea-94cd-34e54c4b0859.PNG)

**Comment by liandexu186** [comment]
I encountered the same problem, could you tell me how to solve it？
