### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by liandexu186** [danini/graph-cut-ransac#15]
Sorry to disturb you, follow the instructions in "readme", when I run the code according to the "examples.ipynb" given, it prompts "AttributeError: module 'pygcransac' has no attribute 'findHomography'"  ,Excuse me, what should I do.

**Comment by ducha-aiki** [comment]
Hi,

Have you installed it via pip install . -e ?

**Comment by liandexu186** [comment]
> Hi,
> 
> Have you installed it via pip install . -e ?

**Comment by liandexu186** [comment]
> Hi,
> 
> Have you installed it via pip install . -e ?

thank you
