### ISSUE TITLE
verify_pygcransac_ess  ，verify_pygcransac_fundam issue

### ISSUE THREAD

**Issue by liandexu186** [danini/graph-cut-ransac#18]
example:
dst_GT:[[[225.54083  -78.85825 ]]
             [[ 29.281984 579.15247 ]]

            [[507.25708  658.83765 ]]

            [[652.5517   151.46173 ]]]
but:
dst_gc_E:
           [[[-0.00518453 -0.00238829]]
           [[-0.00166512 -0.00162377]]
          [[-0.00022065 -0.00130998]]
          [[-0.00118612 -0.00151971]]]
Are there some minor errors in the implementation of these two functions?

**Comment by ducha-aiki** [comment]
Hi,

I haven't really test E version, sorry for that. Only H and F. I will check it when have time.

**Comment by liandexu186** [comment]
Hi,
The F also have some problems

**Comment by liandexu186** [comment]
the number of match is high enough, i think it fit the model well ,but the results is error.

**Comment by liandexu186** [comment]
hi,
I come again,it exists the similar problem in ''pymagsac.fundamental''。
First of all, I am not here to make trouble, because I find that your work really has the potential to make the visual odometer more advanced. I was very interested in it and inspired by it. I want to find out the mistakes by myself. But the code capacity is limited. I know that the work of a PhD is always very busy, but when you have time, please help me. You can think  me as a  fan from a foreign country.

**Comment by danini** [comment]
I sent e-mail, but write here as well. I don't understand term "correct result". Are you comparing directly the obtained E and F matrices? Have you normalized them? Both E and F can have an arbitrary scale. Thus two Es/Fs can be the same even if they do not look the same without normalization. It is better to compare some errors (e.g. symmetric epipolar error) on ground truth inliers or to decompose the matrices to rotation and translation.

**Comment by liandexu186** [comment]
hi,
I promise this is the last time I disturb you, if I want to use ''pygcrasac.findFundamentalMatrix'' get a similar results as "cv2.findfundamentalMatrix",what should I do . I feel very sad now,because i bring you inconvinience.
best 
peter


| |
18604036835
|
|
18604036835@163.com
|
签名由网易邮箱大师定制
On 4/9/2020 14:50，Daniel Barath<notifications@github.com> wrote：

I sent e-mail, but write here as well. I don't understand term "correct result". Are you comparing directly the obtained E and F matrices? Have you normalized them? Both E and F can have an arbitrary scale. Thus two Es/Fs can be the same even if they do not look the same without normalization. It is better to compare some errors (e.g. symmetric epipolar error) on ground truth inliers or to decompose the matrices to rotation and translation.
