### ISSUE TITLE
python setup.py install

### ISSUE THREAD

**Issue by InstantWindy** [danini/graph-cut-ransac#19]
Hi. When I run "python setup.py install", it shows errors as following
![image](https://user-images.githubusercontent.com/23608180/80310597-2d59c900-880e-11ea-9eca-40318c7cb7ae.png)

**Comment by mesperrus** [comment]
Hey any updates on this? Same issue here

**Comment by danini** [comment]
I am trying on my Ubuntu subsystem and, also, in Anaconda and it compiles with no problem. Maybe @ducha-aiki has an idea what this could be.

**Comment by ducha-aiki** [comment]
Could you please specify gcc versions and so on? I am using python 3.7, gcc 9.2.1 and no problem so far.
![image](https://user-images.githubusercontent.com/4803565/89926665-7428ce80-dc05-11ea-9cfb-d8c982e79f70.png)

![image](https://user-images.githubusercontent.com/4803565/89926696-8276ea80-dc05-11ea-954e-82bbebb1a47f.png)

**Comment by danini** [comment]
Has this been solved?
