### ISSUE TITLE
python setup.py install error

### ISSUE THREAD

**Issue by mesperrus** [danini/graph-cut-ransac#22]
I get the following error running
`python setup.py install`

I've tried using GCC 7.1.1 as well as 7.3.1.
Using CentOS 7.7
Also this is within a Docker container with base image centos/devtoolset-7-toolchain-centos7

https://pastebin.com/114ztJm3

**Comment by danini** [comment]
Looks like C++11 is not enabled. Which means that python uses the wrong compiler.
The project should be able to run C++17.

**Comment by mesperrus** [comment]
> Looks like C++11 is not enabled. Which means that python uses the wrong compiler.
> The project should be able to run C++17.

Would one of the dependencies installed from [this list](https://github.com/vcg-uvic/image-matching-benchmark/blob/master/system/conda_env_centos-7.7.yml) possibly be causing this?
