### ISSUE TITLE
Question about the GraphCut based outlier rejection step

### ISSUE THREAD

**Issue by Midsole** [danini/graph-cut-ransac#26]
Hey ‪Daniel,

I got confused with your recent implementation of the `labeling` function in `src/pygcransac/include/GCRANSAC.h` comparing with the version two year ago (7829d27). 

In recent version (f13081e), while constructing the problem graph (Algorithm 3 from your paper), you defined quantity c00, c11, c01, c10  which refers to `e00,e11,e01,e10` in your code. But the quantity `e11` seems to be initialized as `0` (Line841 to Line 878) rather than `e00 = 1.0-0.5 * energy_sum;` which violates the description in Algorithm 3 as well as the way it is implementented in previous versions.

Since the defination of $\lambda$ has changed since certain commit, I am writing to double check. (If someone could provide some references for the new cost function, that would be great 👍 .)

Midsole

**Comment by danini** [comment]
Dear Midsole,

The new version is currently reviewed in a journal. As soon as there is an update on its status, I will share the paper here as well.
The energy setting is however correct and slightly different than the previous one. 

Best,
Daniel

**Comment by danini** [comment]
Here it is: https://ieeexplore.ieee.org/document/9399280
