### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by jiahao68** [danini/graph-cut-ransac#27]
![2021-04-05 17-36-49屏幕截图](https://user-images.githubusercontent.com/58494433/113560608-d2436f80-9635-11eb-92a0-d2c19651eed7.png)
Hi, when I compile the GC-ransac in ubutu16.04, I encounter this problem. Do you have suggestions on how to solve this? Thanks.

**Comment by danini** [comment]
I think the problem is that you dont use C++ 17
