### ISSUE TITLE
a question about experimental results of paper

### ISSUE THREAD

**Issue by xianbeikuku** [danini/graph-cut-ransac#37]
Dear Dr.Barath:
I am a first year master's student in the Wuhan(China) University and my research topic is photogrammtry and computer vision.
I read your paper "Graph-Cut RANSAC: Local Optimization on Spatially Coherent Structures",and run the codes in github.As I find a question about experimental results of paper,I would like to request help from you.
This question is about a pair in the paper, named Fig.4 (a) ExtremeView dataset.In the paper we get a good result. But I can not get a result similar to it(the result in paper), when I test by the codes in github.I show the my reslut in appendix. Is the reason about feature descritor? Because I found that only 19 correspondences were detected in begin.Could you give me some information about this pair?
I would be very grateful indeed for any help you could give me.
best wishes.
Weile Ma
![resulf of paper](https://user-images.githubusercontent.com/79830747/143734863-fe1027f0-03d9-4d64-9ce4-20ecd294653f.png)

![my reslut](https://user-images.githubusercontent.com/79830747/143734877-d67a97f4-c48e-47f5-b6a0-a72e36889f7b.png)

**Comment by ducha-aiki** [comment]
Have you used provided tentative correspondences from here?

http://cmp.felk.cvut.cz/wbs/
![IMG_20211128_093052](https://user-images.githubusercontent.com/4803565/143735319-cd4b064d-7bd9-4d6b-9a55-297683a1cea9.jpg)

**Comment by danini** [comment]
Yeah, those are, in EVD, quite challenging image pairs also for the feature matcher algorithm.
In the paper, I used the correspondences provided in the dataset. I am not sure what you are using for feature detection, probably, SIFT or ORB, but they definitely are not good enough for this problem.

You can find everything at http://cmp.felk.cvut.cz/wbs/ as Dmytro suggested.

**Comment by xianbeikuku** [comment]
> Have you used provided tentative correspondences from here?
> 
> http://cmp.felk.cvut.cz/wbs/ ![IMG_20211128_093052](https://user-images.githubusercontent.com/4803565/143735319-cd4b064d-7bd9-4d6b-9a55-297683a1cea9.jpg)

thanks!
