### ISSUE TITLE
The problem of running example_rigid_transform

### ISSUE THREAD

**Issue by Xinyi-tum** [danini/graph-cut-ransac#38]
Hi! Daniel Barath,

I'm developing a new point set registration method, and I want to compare my method with yours.

However, when I run the example_rigid_transform in python, I got return 
gc_T =  None
gc_mask =  [False False False False False False False False False False False False
 False False False False False False False False False False False]
![image](https://user-images.githubusercontent.com/61148982/204690569-55774fb6-5420-4a50-a57a-7a6edcd6a0cb.png)

I'm confused about this results. Could you help me to solve this problem?
What's more, I'm really confused about the difference between initial_T and ground_truth_T. Why there are two transformation matrixes?

I'm looking forward to your reply!
Sincerely,

Xinyi Li

**Comment by danini** [comment]
Hi Xinyi,

Yeah, I realized a few weeks back that there is some bug on the rigid transformation estimation code. I started looking into it, will hopefully push an update next week. I will let you know when done.

Best,
Daniel

**Comment by danini** [comment]
It should be alright now. I update both the example and the code for running rigid transformation estimation.
You can find the new example here: https://github.com/danini/graph-cut-ransac/blob/master/examples/example_rigid_transform.ipynb

Please let me know if there is any problem.

**Comment by Xinyi-tum** [comment]
Thanks a lot!!
