### ISSUE TITLE
Hello, danini

### ISSUE THREAD

**Issue by yangninghua** [danini/graph-cut-ransac#5]
Hello, danini, in your engineering graph-cut-ransac, I found a mistake, but I can't solve it because I don't quite understand graph-cut-ransac, as shown below. u is a 1*4 matrix, but the program uses it over the boundary.
F->at<float>(0) * u.at<float>(3);
F->at<float>(3) * u.at<float>(4);
F->at<float>(6) * u.at<float>(5);
![image](https://user-images.githubusercontent.com/32252319/43987043-498eb6a6-9d4d-11e8-82ad-8bac7a374ceb.png)

**Comment by yangninghua** [comment]
fundamental_estimator.cpp

**Comment by danini** [comment]
A bit late answer, but thank you for pointing my attention to this bug! The problems was: u is supposed to be the point correspondence (x1 y1 1 x2 y2 1), but I removed the ones and did not changed this part of the code. I hope that it is okay now.

**Comment by MathsionYang** [comment]
i want to know how to solve it??

**Comment by MathsionYang** [comment]
> Hello, danini, in your engineering graph-cut-ransac, I found a mistake, but I can't solve it because I don't quite understand graph-cut-ransac, as shown below. u is a 1*4 matrix, but the program uses it over the boundary.
> F->at(0) * u.at(3);
> F->at(3) * u.at(4);
> F->at(6) * u.at(5);
> ![image](https://user-images.githubusercontent.com/32252319/43987043-498eb6a6-9d4d-11e8-82ad-8bac7a374ceb.png)


您好，怎么解决呢

**Comment by lisongshi** [comment]
> i want to know how to solve it??

you may change the code in essential_estimator.h and fundamental_estimator.h like that: 
u.at(3)  -> u.at(2);
u.at(4)  -> u.at(3);
u.at(5)  -> 1.0;

**Comment by lisongshi** [comment]
> A bit late answer, but thank you for pointing my attention to this bug! The problems was: u is supposed to be the point correspondence (x1 y1 1 x2 y2 1), but I removed the ones and did not changed this part of the code. I hope that it is okay now.

thank you, danini,
i have run it successfully in win whilst i have a issue that i could run it in linux with no change.
it troubles me, may i have your proposal ? thanks a lot
