### ISSUE TITLE
About threshold

### ISSUE THREAD

**Issue by zzxp** [danini/graph-cut-ransac#6]
Hello ，could you tell me that how to determine these thresholds？
![image](https://user-images.githubusercontent.com/26996462/44619030-074e8980-a8b3-11e8-86bb-90d7017b7b2a.png)

**Comment by danini** [comment]
Hey! It is a slightly late answer, but:
probability: the confidence required in the results, same as in RANSAC. 
fps: e.g. if fps = 10, then the algorithm terminates after 1 / 10 secs.
threshold: is simply the RANSAC threshold
lambda: is the weight of spatial coherence, it is set experimentally
neighborhood_size: it is also set experimentally, the radius of the sphere to determine which points are neighbours.
