### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by greenjokers** [danini/graph-cut-ransac#9]
hi danini, I have followed the build instructions, but when i run make,I get
![image](https://user-images.githubusercontent.com/33225979/54589162-d8bb1a80-4a5f-11e9-854c-fda168a505cd.png)
but I already have the cpp in the folder,why?

**Comment by csufangyu** [comment]
you should install "ppl",you can run
`sudo apt-get install libcpprest-dev
`

**Comment by Zhengjun-Du** [comment]
I also encountered this problem, and  I use command "sudo apt-get install libcpprest-dev", but which dosn`t work. how to solve it？

**Comment by danini** [comment]
To be honest, I have not used the algorithm from linux, but you can easily replace each parallel_for cycle by a simple for cycle or using OpenMP. Then you can remove ppl library.

**Comment by Zhengjun-Du** [comment]
thank you danini, before your reply I have solved this problem, from your code ,  I find that the code is writing  with VS2015 or higher version. I do replace each parallel_for cycle by a simple for cycle. I don`t konw what if it will  decrease efficiency apparently.
